---
abstract: 'Determines the maximum weight perfect matching in a weighted complete bipartite graph'
author:
  - 'Martin-Louis Bright <mlbright@gmail.com>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-Kuhn-Munkres
provides:
  Algorithm::Kuhn::Munkres:
    file: lib/Algorithm/Kuhn/Munkres.pm
    version: v1.0.5
requires:
  Test::More: 0
  Test::Perl::Critic: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: v1.0.5
